# Generated by Django 4.0.5 on 2022-06-27 21:24

from django.db import migrations, models
import img_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=img_upload.models.upload_to, verbose_name='Image')),
            ],
        ),
    ]
